package com.eshore.datasupport.metadata.dao;

import java.util.List;

import com.eshore.datasupport.metadata.pojo.R_database_attribute;
import com.eshore.khala.core.data.api.dao.IBaseDao;

/**
*generated by tools 
*
*/
public interface IR_database_attributeDao extends IBaseDao<R_database_attribute> {
	
	/**
	 * 保存attributes
	 * @param list
	 */
	void saveAttributeList(List<R_database_attribute> list);

	/**
	 * 删除r_database
	 * @param id_database
	 */
	void deleteByR_databaseId(Long id_database);

	void updatePort(Long id_database, Integer fd_dk);

}
