package com.eshore.datasupport.metadata.dao;

import com.eshore.datasupport.metadata.pojo.R_database;
import com.eshore.khala.core.data.api.dao.IBaseDao;

/**
*generated by tools 
*
*/
public interface IR_databaseDao extends IBaseDao<R_database> {
	
	/**
	 * 保存database 自增长生成id
	 * @param database
	 */
	public void saveDatabase(R_database database);

	public void setDatabase_type(R_database database, String sjklx);

}
