package com.eshore.datasupport.metadata.dao;

import java.util.HashMap;
import java.util.List;
import java.util.Map;

import com.eshore.datasupport.metadata.pojo.Sjyb;
import com.eshore.khala.common.model.PageConfig;
import com.eshore.khala.core.data.api.dao.IBaseDao;

/**
*generated by tools 
*
*/
public interface ISjybDao extends IBaseDao<Sjyb> {

	/**
	 * 通过条件查询sjyb
	 * @param hashMap
	 * @param pc
	 * @return
	 */
	List<Sjyb> listSjybRecord(Map<String, String> hashMap, PageConfig pc);

}
