package com.eshore.datasupport.metadata.dao;

import java.util.List;
import java.util.Map;

import com.eshore.datasupport.common.vo.YsjzdVo;
import com.eshore.datasupport.metadata.pojo.Wddy;
import com.eshore.khala.common.model.PageConfig;
import com.eshore.khala.core.data.api.dao.IBaseDao;




/**
*generated by tools 
*
*/
public interface IWddyDao extends IBaseDao<Wddy> {
	/**
	 * 得到维度定义表数据
	 * @param meg
	 * @param pc
	 * @return
	 */
	List<Wddy> getwdMessagedata(String meg,PageConfig pc);
	List<Map<String, Object>> getZhutidata();
	/**
	 * 通过ID查询维度定义表
	 * @param idd
	 * @return
	 */
	//List<Map<String, Object>> getmessageDataByid(String idd);
	/**
	 * 通过ID信息字段表
	 * @param megid
	 * @return
	 */
	List<Map<String, Object>> getwddymetadata(String megid);
	List<Map<String, Object>> getIDfromxxfl(String xxbm);
	/**
	 * 通过表名查询维度定义表
	 * @param xxbm
	 * @return
	 */
	List<Wddy> getDataBybm(String xxbm);
	/**
	 * 通过ID和字段名称查询信息字段表
	 * @param megid
	 * @param mc
	 * @return
	 */
	List<YsjzdVo> getwdxxmetadataBymc(String megid,String mc);
	List<YsjzdVo> getwddymetadataForcompare(String megid);
	/**
	 * 添加数据到维度定义表
	 * @param xxuuid
	 * @param xxmc
	 * @param xxms
	 * @param xxbm
	 * @param ti
	 * @param cjr
	 * @param gxr
	 */
	void addxxflMeg(String xxuuid, String xxmc, String xxms, String xxbm,String ti,String cjr,String gxr);
	/**
	 * 更新维度定义表
	 * @param xxmc
	 * @param xxms
	 * @param xxid
	 * @param userid
	 * @param ti
	 */
	void  updateMegdata(String xxmc,String xxms,String xxid,String userid,String ti);
	/**
	 * 通过jdbc连接数据库，执行sql语句
	 * @param url  jdbc连接地址
	 * @param driveclass jdbc驱动
	 * @param sqls  执行sql 
	 * @param username jdbc连接用户名
	 * @param password  jdbc连接密码
	 * @return
	 */
	String editxxmetadata(String url,String driveclass,List<String> sqls,String username,String password);


}
