package com.eshore.datasupport.metadata.dao;

import java.util.List;
import java.util.Map;

import com.eshore.datasupport.common.vo.YsjzdVo;
import com.eshore.datasupport.metadata.pojo.Xxfl;
import com.eshore.datasupport.metadata.vo.MessageVo;
import com.eshore.datasupport.metadata.vo.RequestParams;
import com.eshore.khala.common.model.PageConfig;
import com.eshore.khala.core.data.api.dao.IBaseDao;




/**
*generated by tools 
*
*/
public interface IXxflDao extends IBaseDao<Xxfl> {
	/**
	 * 查询信息分类表数据
	 * @param zt
	 * @param meg
	 * @param pc
	 * @return
	 */
	List<MessageVo> getMessagedata(String zt,String meg,PageConfig pc);
	List<Map<String, Object>> getZhutidata();
	//List<Map<String, Object>> getmessageDataByid(String idd);
	/**
	 * 通过ID查询信息分类表,并将数据存储到pojo类中
	 * @param megid
	 * @return
	 */
	 List<YsjzdVo> getxxmetadata(String megid);
	 /**
	  * 通过ID查询信息字段表
	  * @param megid
	  * @return
	  */
	 List<Map<String, Object>>  getmetaDatainpage(String megid);
	 /**
	  * 通过ID和字段名称查询信息字段表
	  * @param megid
	  * @param mc
	  * @return
	  */
	List<YsjzdVo> getxxmetadataBymc(String megid,String mc);
	List<Map<String, Object>> getIDfromxxfl(String xxbm);
	List<Xxfl> getDataBybm(String xxbm);
	/**
	 * 添加数据到信息分类表
	 * @param params
	 * @param ti
	 * @param cjr
	 * @param gxr
	 */
	void addxxflMeg(RequestParams params,String ti,String cjr,String gxr);
	/**
	 * 更新信息分类表
	 * @param xxzt
	 * @param xxmc
	 * @param xxms
	 * @param xxid
	 * @param userid
	 * @param ti
	 */
	void  updateMegdata(String xxzt,String xxmc,String xxms,String xxid,String userid,String ti);
	/**
	 * 通过jdbc连接数据库，执行sql语句
	 * @param url  jdbc连接地址
	 * @param driveclass jdbc驱动
	 * @param sqls  执行sql 
	 * @param username jdbc连接用户名
	 * @param password  jdbc连接密码
	 * @return
	 */
	String editxxmetadata(String url,String driveclass,List<String> sqls,String username,String password);
	List<Map<String,Object>> findAnyBysjyId(String ztid);

}
