package com.eshore.datasupport.metadata.dao;

import com.eshore.datasupport.metadata.pojo.Xxzd;
import com.eshore.khala.core.data.api.dao.IBaseDao;




/**
*generated by tools 
*
*/
public interface IXxzdDao extends IBaseDao<Xxzd> {
	 

}
