package com.eshore.datasupport.metadata.dao;

import java.util.List;
import java.util.Map;

import com.eshore.datasupport.common.vo.YsjzdVo;
import com.eshore.datasupport.metadata.pojo.Sjyb;
import com.eshore.datasupport.metadata.pojo.Ysjzd;
import com.eshore.datasupport.metadata.vo.DataSourceTs;
import com.eshore.khala.core.data.api.dao.IBaseDao;

/**
 * generated by tools
 */
public interface IYsjzdDao extends IBaseDao<Ysjzd> {
    List<Map<String, Object>> editysjzdData(String parm1, String parm2);

    int saveysjzdData(String pa1, String pa2);

    List<Ysjzd> getysjzdData(String bm);

    /**
     * 通过jdbc远程查找表的字段信息
     *
     * @param dirvename
     * @param url
     * @param sjyb
     * @param bm
     * @return
     */
    List<YsjzdVo> getdatayuanByid(String dirvename, String url, Sjyb sjyb, String bm);

    /**
     * 通过表名查元数据表
     *
     * @param name
     * @param sjy
     * @return
     */
   // List<Map<String, Object>> getysjbidByname(String name, String sjy);

    /**
     * 通过ID和表名查询元数据字段表，并封装成pojo类
     *
     * @param id
     * @param bm
     * @param sjy
     * @return
     */
    List<YsjzdVo> getysjzdDataBybm(String id, String bm, String sjy);

    /**
     * 获取DataSourceTs
     *
     * @param id
     * @return
     */
    List<DataSourceTs> getDataSourceTs(String id);
}
