package com.eshore.datasupport.metadata.dao;

import java.util.List;
import java.util.Map;

import com.eshore.datasupport.common.vo.YsjbDescribeVo;
import com.eshore.datasupport.metadata.pojo.Sjyb;
import com.eshore.datasupport.metadata.pojo.Ysjb;
import com.eshore.datasupport.metadata.pojo.Ysjzd;
import com.eshore.khala.common.model.PageConfig;
import com.eshore.khala.core.data.api.dao.IBaseDao;




/**
*generated by tools 
*
*/
public interface IYsjbDao extends IBaseDao<Ysjb> {
	/**
	 * 查询元数据表
	 * @param sjy
	 * @param pc
	 * @return
	 */
	List<Ysjb> getmetedataTable(String sjy,PageConfig pc);
	 //List<Map<String, Object>>    getDatayuan();
	 List<Map<String,Object>> findAnyBysjyId(String sjy_id);
	 /**
	  * 通过jdbc连接远程查询表的描述信息
	  * @param drivename
	  * @param url
	  * @param sjyb
	  * @param bm
	  * @return
	  */
	 List<YsjbDescribeVo> getbiaoSql(String drivename,String url,Sjyb sjyb,String bm);


	/**
	 * 获取相对应的表的描述信息
	 * @param fd_sjy_id 数据源主键
	 * @param bm 表名
	 * @return
	 */
	String getTableComment(String fd_sjy_id,String bm);

	/**
	 * 获取第一个匹配的ID
	 * @param fd_bm 表名
	 * @param fd_ms 描述
	 * @return
	 */
	String getTableId(String fd_bm,String fd_ms);

	/**
	 * 通过表名，数据源ID查询元数据表
	 * @param name 表名
	 * @param sjy  数据源ID
	 * @return
	 */
	List<Ysjb> getysjbidByname(String name, String sjy);
}
