package com.eshore.datasupport.common.dao;

import java.util.List;
import java.util.Map;

import com.eshore.datasupport.common.pojo.Gjsj;
import com.eshore.khala.common.model.PageConfig;
import com.eshore.khala.core.data.api.dao.IBaseDao;

/**
*generated by tools 
*
*/
public interface IGjsjDao extends IBaseDao<Gjsj> {

	List<Map<String, String>> ajaxHomeGjInfo(PageConfig pc);

}
