package com.eshore.datasupport.common.dao;

import java.util.List;
import java.util.Map;

import com.eshore.datasupport.common.pojo.Gj;
import com.eshore.datasupport.common.pojo.Jkdy;
import com.eshore.datasupport.common.vo.JkdyVo;
import com.eshore.khala.common.model.PageConfig;
import com.eshore.khala.core.data.api.dao.IBaseDao;

/**
*generated by tools 
*
*/
public interface IJkdyDao extends IBaseDao<Jkdy> {

	/**
	 * 获取接口记录
	 * @param jkname 参数
	 * @param pc 分页参数
	 * @return 接口纪录list
	 */
	List<JkdyVo> getInterfaceMeg(String jkname, PageConfig pc);

	List<Jkdy> getDataBynamecode(String code);

}
