package com.eshore.datasupport.common.dao;

import java.util.List;
import java.util.Map;

import com.eshore.datasupport.common.pojo.Yhb;
import com.eshore.khala.common.model.PageConfig;
import com.eshore.khala.core.data.api.dao.IBaseDao;

/**
*generated by tools 
*
*/
public interface IYhbDao extends IBaseDao<Yhb> {

	/**
	 * 获取用户信息
	 * @param params  传入参数
	 * @param pc 分页参数
	 * @return 用户list
	 */
	List<Yhb> listByYhmc(Map<String,String> params,PageConfig pc);

	/**
	 * 通过登陆名称获取用户信息
	 * @param fd_dlmc 登录名称
	 * @return 用户信息
	 */
	Yhb getYhbByFd_dlmc(String fd_dlmc);

}
