package com.eshore.datasupport.common.dao;

import java.util.List;
import java.util.Map;

import com.eshore.datasupport.common.pojo.Yhzy;

import com.eshore.khala.core.data.api.dao.IBaseDao;

/**
*generated by tools 
*
*/
public interface IYhzyDao extends IBaseDao<Yhzy> {

	/**
	 * 获取菜单信息 
	 * @param id 用户id
	 * @return 菜单list
	 */
	List listxMenuById(String id);

	/**
	 * 
	 * @param id
	 * @return
	 */
	List<Object[]> findMenuListById(String id);

	/**
	 * 获取指定用户的菜单
	 * @param fd_yhid 用户id
	 * @return 用户信息
	 */
	List<Yhzy> getSpecifyYhzy(String fd_yhid);

	/**
	 * 
	 * @param id
	 * @return
	 */
	List<Map<String, Object>> ajaxZtreeMenuListById(String id);

	List<Yhzy> getYhzyRecordByZyid(String zyid);

}
