package com.eshore.datasupport.common.dao;

import java.util.List;

import com.eshore.datasupport.common.pojo.Zypz;

import com.eshore.khala.core.data.api.dao.IBaseDao;

/**
*generated by tools 
*
*/
public interface IZypzDao extends IBaseDao<Zypz> {

	/**
	 * 获取子节点信息
	 * @param fd_fjid 传入父节点的id
	 * @return
	 */
	List<Zypz> getChildrenZypz(String fd_fjid);

}
