package com.eshore.datasupport.task.dao;

import java.util.List;
import java.util.Map;

import com.eshore.datasupport.task.pojo.Rwb;
import com.eshore.datasupport.task.vo.TaskKettleVo;
import com.eshore.khala.common.model.PageConfig;
import com.eshore.khala.core.data.api.dao.IBaseDao;

/**
*generated by tools 
*
*/
public interface IRwbDao extends IBaseDao<Rwb> {
	/**
	 * 通过任务id查询任务对象
	 * @param rwb 任务id
	 * @return	TaskKettleVo 
	 */
	public TaskKettleVo findRWJOB(Rwb rwb);
	
	/**
	 * 
	 * @param date
	 * @param id
	 */
	public void updateSJC(String startTime,String endTime,String id);
	 
	/**
	 * 获取采集任务
	 * @param ids 
	 * @param qzrw_mc 
	 * @return 采集对象List
	 */
	public List<Map<String, Object>> getCollectionTaskList(PageConfig pc, String ids, String qzrw_mc);

	public List<Map<String, Object>> getSelectedCollectTaskList(String id);

	public Map<String, Object> getQzrwInfo(String id_temp);

}
