package com.eshore.datasupport.task.dao;

import java.util.Date;
import java.util.List;
import java.util.Map;

import com.eshore.datasupport.task.pojo.Rwsl;
import com.eshore.datasupport.task.vo.ExceptionRecordVo;
import com.eshore.khala.common.model.PageConfig;
import com.eshore.khala.core.data.api.dao.IBaseDao;

/**
*generated by tools 
*
*/
public interface IRwslDao extends IBaseDao<Rwsl> {
	public Rwsl findLastRwsl(String dsJobId,Date sjc);
	public void saveRWSL(Rwsl rwsl);
	/**
	 * 查询日志运行的结果数据
	 * @param gzm
	 * @param pc
	 * @param lx
	 * @return
	 */
	List<Map<String, Object>>   getRulemonitordata(String gzm,PageConfig pc,int lx);
	/**
	 * 通过任务实例表查询任务运行的成功次数
	 * @param idd
	 * @return
	 */
	Map   getWorkcount(String idd);
	/**
	 * 通过排序得到任务的运行时间
	 * @param idd
	 * @return
	 */
	//List<Map<String, Object>>   getRuledetailtime(String ids);
	
	//List<Map<String, Object>>   getYcjuname(String ids);
	/**
	 * 通过ID查询任务实例表
	 * @param idd
	 * @param pc
	 * @return
	 */
	List<Rwsl>   getRuledetail(String idd,PageConfig pc);
	/**
	 * 查询异常记录表
	 * @param idd
	 * @param pc
	 * @return
	 */
	List<ExceptionRecordVo>   getYcjudetail(String idd,PageConfig pc);
	//List<Map<String, Object>>   getYcjuofycsj(String idd);
		
	//获取首页数据库采集数量，异常数量统计信息学
	public List<Map<String, Object>> ajaxRwslStatistics(PageConfig pc);
	
	/**
	 * 首页图表展示rwsl统计信息
	 * @return 返回统计信息
	 */
	public List<Map<String, Object>> ajaxHomeRwslStatisticForEchart();
}
