package com.eshore.datasupport.task.dao;

import java.util.List;
import java.util.Map;

import com.eshore.datasupport.task.pojo.Ycjl;
import com.eshore.khala.common.model.PageConfig;
import com.eshore.khala.core.data.api.dao.IBaseDao;

/**
*generated by tools 
*
*/
public interface IYcjlDao extends IBaseDao<Ycjl> {
	List<Map<String, Object>>  exportYcdata(String idd);
}
